In [1]:
import pandas as pd
import importlib
import sol_vibes_financial as svf

In [48]:
#importlib.reload(fp)

# Read raw data
#data = pd.read_csv("data_files/February 2025/February 2025 Transactions.csv")
data = pd.read_csv("data_files/January 2025/january transactions fifo.csv")

# Prep raw data
data.fillna(0)

,Date,Type,Transaction ID,Received Quantity,Received Currency,Received Cost Basis (USD),Received Wallet,Received Address,Received Comment,Sent Quantity,...,Sent Cost Basis (USD),Sent Wallet,Sent Address,Sent Comment,Fee Amount,Fee Currency,Fee Cost Basis (USD),Realized Return (USD),Fee Realized Return (USD),Transaction Hash
0,01/31/2025 19:16:38,RECEIVE,0194cde5-177b-7e3c-84a6-61de25af3f6a,1.000000e-06,SOL,0.00,Casper,DTFhyarmG9UJn2bnt29GLjcEKfPEFRQC7YCgywuhapAv,0.0,0.000000,...,0.00,0,0,0.0,0.000000,0,0.0,0.00,0.0,9yzWtvrt3Jfg4KAzJLqydTEr3UHuz56PhRb4HvnxAqTcbE...
1,01/31/2025 15:09:09,RECEIVE,0194cde5-00e9-71c4-9f09-f8e618f25c11,1.000000e-05,SOL,0.00,Casper,DTFhyarmG9UJn2bnt29GLjcEKfPEFRQC7YCgywuhapAv,0.0,0.000000,...,0.00,0,0,0.0,0.000000,0,0.0,0.00,0.0,oHudFvFcL82LzG4wKhWfUg7G43mvVmo5eUjx3auXfNuuNL...
2,01/31/2025 15:07:04,RECEIVE,0194cde5-11d3-7fca-b0db-d9b3ed9c5ce5,1.000000e-05,SOL,0.00,Casper,DTFhyarmG9UJn2bnt29GLjcEKfPEFRQC7YCgywuhapAv,0.0,0.000000,...,0.00,0,0,0.0,0.000000,0,0.0,0.00,0.0,3josVxbXLGaZAdvXma8hzXwcJZCdwVw6z7FpGhogouY8de...
3,01/31/2025 15:06:32,SEND,0194cde5-057e-7994-81e7-57380ce2aecd,0.000000e+00,0,0.00,0,0,0.0,0.106000,...,23.28,Casper,DTFhyarmG9UJn2bnt29GLjcEKfPEFRQC7YCgywuhapAv,0.0,0.000005,SOL,0.0,2.05,0.0,Qzg9GJQG4gCFDqJUwBBodkNw2Mz6n6CAhZ66VVkBrv817Q...
4,01/31/2025 15:04:48,RECEIVE,0194cde5-007a-7fef-aff9-1af3f8d14916,1.000000e-05,SOL,0.00,Casper,DTFhyarmG9UJn2bnt29GLjcEKfPEFRQC7YCgywuhapAv,0.0,0.000000,...,0.00,0,0,0.0,0.000000,0,0.0,0.00,0.0,2tZ9SeoJ16EDxQBcvxPh3pKDbmm8dWmVwdgTMTVeiRSm17...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,01/02/2025 01:36:51,RECEIVE,0194cde5-0625-7d59-9bb1-89523241eaab,1.000000e-07,SOL,0.00,Casper,DTFhyarmG9UJn2bnt29GLjcEKfPEFRQC7YCgywuhapAv,0.0,0.000000,...,0.00,0,0,0.0,0.000000,0,0.0,0.00,0.0,5G618Sck2xSsDigCSnYUGyvZ938A6pvjsfk6zLeEC2gqZE...
281,01/02/2025 01:36:47,SEND,0194cde5-09ee-71cc-acac-d21b75806af2,0.000000e+00,0,0.00,0,0,0.0,15.000000,...,3513.00,Casper,DTFhyarmG9UJn2bnt29GLjcEKfPEFRQC7YCgywuhapAv,0.0,0.000015,SOL,0.0,-604.93,0.0,4d7YEP1BqfFtMuYS5muynAcuPpqvVpaEAv5SjXwJy8bHWg...
282,01/02/2025 01:01:11,RECEIVE,0194cde5-01b8-7924-a310-5cc87fec1242,1.000000e-07,SOL,0.00,Casper,DTFhyarmG9UJn2bnt29GLjcEKfPEFRQC7YCgywuhapAv,0.0,0.000000,...,0.00,0,0,0.0,0.000000,0,0.0,0.00,0.0,4tikidnVyLfaqxkgXzhmKtNe2fzwLmL4RGAmGT3gPpgzaK...
283,01/02/2025 00:59:20,RECEIVE,0194cde5-176c-7867-87cf-dfc0574f034c,1.611631e+01,SOL,3124.50,Casper,DTFhyarmG9UJn2bnt29GLjcEKfPEFRQC7YCgywuhapAv,0.0,0.000000,...,0.00,0,0,0.0,0.000000,0,0.0,0.00,0.0,5zDfGTWJinYcR4qxiimeu9rr7t4HFzG9DUff6TbuFDqcM1...
284,01/01/2025 06:24:03,MULTI_TOKEN_TRADE,0194a2c6-8728-714c-8b83-31535dc48d2b,1.389357e-02,SOL,2.63,Cold Storage,JCr73pkangQ5YaVpjqMweNJvX9Qc3eUzA9YZALz7JxA8,0.0,0.013894,...,0.00,Cold Storage,JCr73pkangQ5YaVpjqMweNJvX9Qc3eUzA9YZALz7JxA8,0.0,0.000000,0,0.0,0.00,0.0,29nY6AjaZDsLciRVinKf7T2BxsijhFWDBYWj3nY1SyLDUm...

In [49]:
importlib.reload(svf)

x = svf.calculate_transaction_data(data)

for y in x:
    print(y)
    print(x[y])
    print('\n')

receipts
{'SOL': {'qty': 425.45339348, 'cb': 93793.45, 'rg': 0, 'rl': 0}}


rewards
{'SOL': {'qty': 2.21081165, 'cb': 507.36, 'rg': 0, 'rl': 0}}


transfers
{'SOL': {'qty': 100.0, 'cb': 20432.16, 'rg': 0, 'rl': 0}}


payments
{'USDC': {'qty': 19058.528025, 'cb': 19057.22, 'rg': 0, 'rl': -0.08}, 'SOL': {'qty': 126.21757, 'cb': 28281.28, 'rg': 262.25, 'rl': -3520.24}}


stakings
{'SOL': {'qty': 285.00456576, 'cb': 0.0, 'rg': 0, 'rl': 0}}


investments
{'SOL': {'qty': 185.6565381, 'cb': 39215.93, 'rg': 0, 'rl': 0}}


trades
{nan: {'sen_qty': 0, 'sen_cb': 0, 'rg': 0, 'rl': 0, 'rec_qty': 0, 'rec_cb': 0}, 'USDC': {'sen_qty': 0, 'sen_cb': 0, 'rg': 0, 'rl': 0, 'rec_qty': 58644.506947, 'rec_cb': 58640.5}, 'SOL': {'sen_qty': 254.03292885, 'sen_cb': 49138.41, 'rg': 9566.33, 'rl': -65.41, 'rec_qty': 0, 'rec_cb': 0}}

In [50]:
# So how much money did we receive? 
importlib.reload(svf)

a = svf.pl_table(x)

a

-Total Revenue:  104129.39

-Total Expenses:  47535.340000000004

Profit:  56594.049999999996

      Type                             Source    Amount
0   Income                       SOL receipts  93793.45
1   Income                        SOL rewards    507.36
2   Income        SOL trades (realized gains)   9566.33
3  Expense       SOL trades (realized losses)    -65.41
4   Income     USDC payments (realized gains)      0.00
5  Expense    USDC payments (realized losses)      0.08
6  Expense  USDC payments (fair market value)  19057.14
7   Income      SOL payments (realized gains)    262.25
8  Expense     SOL payments (realized losses)   3520.24
9  Expense   SOL payments (fair market value)  25023.29

In [ ]:
# So how much money did we spend/lose?

In [25]:
# So how much money did we make? 
importlib.reload(svf)

svf.accounting_stats(x)

Accounting Profit/Loss

Income (USD):
--- USDT receipts:	 249.7
--- SOL receipts:	 45495.729999999996
--- SOL rewards:	 504.79
--- USDC payments (realized gains):	 0.08
--- SOL payments (realized gains):	 61.42
-Total:  46311.719999999994

Expenses (USD):
--- USDC payments (fair market value):	 750.0300000000001
--- USDC payments (realized losses):	 0
--- SOL payments (fair market value):	 12461.68
--- SOL payments (realized losses):	 518.0699999999999
-Total:  13668.28

Profit:  32643.439999999995

In [52]:
# How are assets flowing?
importlib.reload(svf)

y = svf.asset_flow_table(x)
y

,name,receipts,rewards,payments,investments,trade_for,trade_away,cash_out,total_positive,total_negative,net_flow
0,USDC,0.000000,0.000000,19058.528025,0.000000,58644.506947,0.000000,0,58644.506947,19058.528025,39585.978922
1,SOL,425.453393,2.210812,126.217570,185.656538,0.000000,254.032929,0,613.320743,380.250499,233.070244